### ISSUE TITLE
please add manual for the game

### ISSUE THREAD

**Issue by Sonic1paRadise** [DerekPascarella/CoolCoolToon-EnglishPatchDreamcast#2]
this
![20200629194454](https://github.com/DerekPascarella/CoolCoolToon-EnglishPatchDreamcast/assets/51707249/32f37518-74e0-4105-b34b-5e8a77f4e415)
is the only image of the manual i have ever found.
please submit manual to segaretro.

**Comment by DerekPascarella** [comment]
This is not a bug report. I have no plans to scan manual, sorry.
